from turtle import *
import turtle

name=textinput('receita federal','Digite o nome:\n')
name.lower()

arrayName = list(name)

for letter in arrayName:
    if 'a' == letter:
        delay(20)
        lt(90)
        rt(25)
        fd(100)
        rt(120)
        fd(100)
        rt(180)
        fd(50)
        lt(65)
        fd(50)
        clear()
        reset()
   
    if 'b' == letter:
        delay(20)
        rt(90)
        fd(200)
        lt(90)
        fd(150)
        lt(20)
        fd(20)
        lt(20)
        fd(20)
        lt(20)
        fd(20)
        lt(20)
        fd(20)
        lt(20)
        fd(20)
        lt(20)
        fd(20)
        lt(20)
        fd(20)
        lt(20)
        fd(20)
        lt(20)
        fd(150)
        rt(90)
        fd(120)
        rt(90)
        fd(100)
        rt(20)
        fd(25)
        rt(20)
        fd(25)
        rt(20)
        fd(25)
        rt(20)
        fd(25)
        rt(20)
        fd(23)
        rt(20)
        fd(18)
        rt(20)
        fd(20)
        rt(20)
        fd(25)
        rt(20)
        fd(100)
        clear()
        reset()

    if 'c' == letter:
        delay(20)
        lt(180)
        fd(90)
        lt(90)
        fd(120)
        lt(90)
        fd(90)
        clear()
        reset()

    if 'd' == letter:
        reset()

    if 'e' == letter:
        delay(20)
        lt(90)
        fd(100)
        rt(90)
        fd(50)
        bk(50)
        rt(90)
        fd(50)
        lt(90)
        fd(50)
        bk(50)
        rt(90)
        fd(50)
        lt(90)
        fd(50)
        clear()
        reset()

    if 'f' == letter:
        delay(20)
        lt(90)
        fd(100)
        rt(90)
        fd(50)
        lt(180)
        fd(50)
        lt(90)
        fd(40)
        lt(90)
        fd(40)
        lt(180)
        fd(40)
        clear()
        reset()

    if 'g' == letter:
        delay(20)
        rt(180)
        fd(100)
        lt(90)
        fd(150)
        lt(90)
        fd(100)
        lt(90)
        fd(75)
        lt(90)
        fd(50)
        clear()
        reset()

    if 'h' == letter:
        delay(20)
        lt(90)
        fd(100)
        lt(180)
        fd(200)
        lt(180)
        fd(100)
        lt(90)
        fd(100)
        lt(90)
        fd(100)
        lt(180)
        fd(200)
        clear()
        reset()
    
    if 'i' == letter:
        delay(20)
        lt(90)
        fd(100)
        clear()
        reset()
        
    if 'j' == letter:
        delay(20)
        lt(90)
        fd(100)
        lt(90)
        fd(100)
        rt(180)
        forward(100)
        forward(100)
        lt(180)
        fd(100)
        lt(90)
        fd(200)
        rt(90)
        fd(120)
        rt(90)
        fd(50)
        clear()
        reset()
    
    if 'k' == letter:
        delay(20)
        lt(90)
        fd(150)
        lt(180)
        fd(80)
        lt(150)
        fd(90)
        lt(180)
        fd(90)
        lt(70)
        fd(100)
        clear()
        reset()
    
    if 'l' == letter:
        delay(20)
        rt(90)
        fd(150)
        lt(90)
        fd(120)
        clear()
        reset()
    
    if 'm' == letter:
        delay(20)
        lt(90)
        fd(150)
        rt(150)
        fd(100)
        lt(120)
        fd(100)
        rt(150)
        fd(150)
        clear()
        reset()
    
    if 'n' == letter:
        delay(20)
        lt(90)
        fd(100)
        rt(150)
        fd(115)
        lt(148)
        fd(100)
        clear()
        reset()
    
    if 'o' == letter:
        delay(20)
        fd(5)
        lt(-5)
        fd(5)
        hideturtle()
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        fd(40)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        fd(40)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        lt(-5)
        fd(5)
        clear()
        reset()
    
    if 'p' == letter:
        delay(20)
        hideturtle()
        lt(90)
        fd(150)
        rt(90)
        fd(55)
        rt(10)
        fd(5)
        rt(10)
        fd(5)
        rt(10)
        fd(5)
        rt(10)
        fd(5)
        rt(10)
        fd(5)
        rt(10)
        fd(5)
        rt(10)
        fd(5)
        rt(10)
        
    if 'q' == letter:
        delay(20)
        rt(90)
        fd(100)
        lt(90)
        fd(100)
        lt(90)
        fd(200)
        lt(90)
        fd(100)
        lt(90)
        fd(100)
        lt(180)
        fd(100)
        lt(208)
        fd(280)
        clear()
        reset()
    
    if 'r' == letter:
        delay(20)
        lt(90)
        fd(100)
        rt(90)
        fd(70)
        rt(90)
        fd(40)
        rt(90)
        fd(70)
        lt(140)
        fd(90)
        clear()
        reset()
    
    if 's' == letter:
        delay(20)
        fd(90)
        rt(180)
        fd(90)
        lt(90)
        fd(90)
        lt(90)
        fd(90)
        lt(270)
        fd(90)
        lt(270)
        fd(90)
        clear()
        reset()
    
    if 't' == letter:
        delay(20)
        lt(90)
        fd(200)
        rt(90)
        fd(90)
        back(180)
        clear()
        reset()

    if 'u' == letter:
        delay(20)
        lt(90)
        fd(200)
        lt(180)
        fd(200)
        lt(90)
        fd(100)
        lt(90)
        fd(200)
        clear()
        reset()
    
    if 'v' == letter:
        delay(20)
        lt(125)
        fd(100)
        lt(900)
        fd(100)
        right(600)
        fd(100)
        clear()
        reset()
    
    if 'w' == letter:
        delay(20)
        rt(70)
        fd(100)
        rt(220)
        fd(100)
        rt(140)
        fd(100)
        rt(220)
        fd(100)
        clear()
        reset()

    if 'x' == letter:
        delay(20)
        rt(70)
        fd(100)
        back(50)
        rt(220)
        fd(50)
        back(100)
        clear()
        reset()
    
    if 'y' == letter:
        delay(20)
        rt(60)
        fd(100)
        lt(120)
        fd(100)
        rt(180)
        fd(100)
        lt(20)
        fd(100)
        clear()
        reset()
    
    if 'z' == letter:
        delay(20)
        fd(90)
        lt(240)
        fd(180)
        rt(240)
        fd(90)
        clear()
        reset()
